### ISSUE TITLE
Suggestion: borrow from Miliconvert

### ISSUE THREAD

**Issue by bradh** [mil-oss/MTFXML#2]
See http://adullact.net/projects/miliconvert/ (much of it in French) - conversion tools for Eclipse, apparently sponsored by DGA. 

The project appears dead, but they do provide a subset of the ADaT-P3 schemas (BL11 and BL12) as a direct download (http://adullact.net/frs/download.php/file/5106/xsd.tar.gz).

Public data reference (and appropriate scripts to pull it) could help the MTFXML project along with testing.

**Comment by Neutron** [comment]
Thanks Brad!  Good looking out.. but this project supports the official releases for US and NATO MTF and we have access to those schema for testing and validation.  We can't provide them on Github because they are release restricted.  I'm pretty sure the ones you found are not supposed to be public .. so we really can't use them.  

We are working on using XML tagging to specify releasability at the node level and exclude the sensitive stuff.  Once we do this we can post releasable official versions of US and NATO MTF and invite the mil-oss community and all interested developers to get involved.
